class TestData {
    get dataType() {
        return {
        firstName: 'Jacek',
        lastName: 'Marek',
        eMail: "ab@cd.pl",
        comments: "Test comment :)",
        validEmail: ["example@email.com",
        "example.first.middle.lastname@email.com",
        "example@subdomain.email.com",
        "example+firstname+lastname@email.com",
        "example@234.234.234.234",
        "example@[234.234.234.234]",
        "“example”@email.com",
        "0987654321@example.com",
        "example@email-one.com",
        "_______@email.com",
        "example@email.name",
        "example@email.museum",
        "example@email.co.jp",
        "example.firstname-lastname@email.com",
        "Valid Email Addresses that appear at glance to be invalid",
        "extremely.”odd/unusual”@example.com",
        "extremely.unusual.”@”.unusual.com@example.com",
        "very.”(),:;<>[]”.VERY.”very@\\ “very”.unusual@strange.email.example.com"],
        invalidEmail: ["plaintextaddress",
        "@#@@##@%^%#$@#$@#.com",
        "@email.com",
        "John Doe <example@email.com>",
        "example.email.com",
        "example@example@email.com",
        ".example@email.com",
        "example.@email.com",
        "example…example@email.com",
        "おえあいう@example.com",
        "example@email.com (John Doe)",
        "example@email",
        "example@-email.com",
        "example@email.web",
        "example@111.222.333.44444",
        "example@email…com",
        "CAT…123@email.com",
        "”(),:;<>[\]@email.com",
        "obviously”not”correct@email.com",
        "example\ is”especially”not\allowed@email.com"],
        dropdownValues: ["JAVA", "C#", "Python", "SQL", "Eclipse", "Maven", "TestNG", "JUnit", "HTML", "CSS", "JavaScript", "JQuery"],
        goBackForDays: 1000,
        food: ["Chips", "Chicken", "Granola", "Grapes", "French toast", "French dip"]
        }
    }
}

export const testData = new TestData()